# Conect with DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/dba_lab1
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

#JDBC config
spring.main.banner-mode=off
spring.jpa.enabled=false

# Logging activated
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.datasource.DataSourceUtils=DEBUG
